version: '2'

services:
  app:
    container_name: docker-nest-mongo
    restart: always
    build: .
    ports:
      - '3200:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
